# Generated by Django 4.1.5 on 2023-01-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='img',
            field=models.ImageField(default=1, upload_to='photos'),
            preserve_default=False,
        ),
    ]
