# Generated by Django 4.1.5 on 2023-01-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0002_fashion_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='price',
            field=models.TextField(),
        ),
    ]
